/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zmq_tx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(93d27d577a0fa2c769bb79152d0d8906)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gr_zmq_if/zmq_tx.h>
// pydoc.h is automatically generated in the build directory
#include <zmq_tx_pydoc.h>

void bind_zmq_tx(py::module& m)
{

    using zmq_tx    = gr::gr_zmq_if::zmq_tx;


    py::class_<zmq_tx, gr::block, gr::basic_block,
        std::shared_ptr<zmq_tx>>(m, "zmq_tx", D(zmq_tx))

        .def(py::init(&zmq_tx::make),
           D(zmq_tx,make)
        )
        



        ;




}








