/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zmq_if.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(87248058d3266e127aba51a915f52a6d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/doa4rfc/zmq_if.h>
// pydoc.h is automatically generated in the build directory
#include <zmq_if_pydoc.h>

void bind_zmq_if(py::module& m)
{

    using zmq_if    = gr::doa4rfc::zmq_if;


    py::class_<zmq_if, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<zmq_if>>(m, "zmq_if", D(zmq_if))

        .def(py::init(&zmq_if::make),
           D(zmq_if,make)
        )
        



        ;




}








