/**
 * @file sc_standards.c
 * @author Felix Schuelke (flxscode@gmail.com)
 *
 * @brief Standard-specific preset initializers for the scframesync
 * configuration; see sc_standards.h.
 *
 * @version 0.1
 * @date 2026-07-06
 *
 * @copyright Copyright (c) 2026
 */

#include <math.h>
#include <complex.h>

#include <liquid.h>
#include "sc_standards.h"

// initialize GPS L1 C/A code (IS-GPS-200, section 3.3.2.3):
// Gold code of length 1023, generated by XOR of the G1 (x^10+x^3+1) and G2
// (x^10+x^9+x^8+x^6+x^3+x^2+1) maximal-length sequences, where the G2 output
// is the XOR of two satellite-specific register stages (phase-select taps).
// Chips are mapped to BPSK symbols (bit 0 -> +1, bit 1 -> -1).
//  _prn      :   satellite PRN number (1..32)
//  _preamble :   output C/A code chips, [size: 1023 x 1]
int scframesync_init_gps_l1ca(unsigned int           _prn,
                              liquid_float_complex * _preamble)
{
    // validate input (phase-select taps defined for the 32 GPS satellites)
    if (_prn < 1 || _prn > 32)
        return liquid_error(LIQUID_EICONFIG,"scframesync_init_gps_l1ca(), PRN number must be in 1..32");

    // G2 phase-select taps per PRN (IS-GPS-200, Table 3-Ia), 1-based stages
    static const unsigned int taps[32][2] = {
        {2,6},{3,7},{4,8},{5,9},{1,9},{2,10},{1,8},{2,9},
        {3,10},{2,3},{3,4},{5,6},{6,7},{7,8},{8,9},{9,10},
        {1,4},{2,5},{3,6},{4,7},{5,8},{6,9},{1,3},{4,6},
        {5,7},{6,8},{7,9},{8,10},{1,6},{2,7},{3,8},{4,9}};
    unsigned int t1 = taps[_prn-1][0];
    unsigned int t2 = taps[_prn-1][1];

    // shift registers, index 1..10 (index 0 unused), initialized to all ones
    unsigned int g1[11], g2[11];
    unsigned int i, j;
    for (i=1; i<=10; i++) {
        g1[i] = 1;
        g2[i] = 1;
    }

    float complex * S = (float complex*) _preamble;
    for (i=0; i<GPS_L1CA_CODE_LEN; i++) {
        // chip: G1 output XOR phase-selected G2 output
        unsigned int chip = g1[10] ^ (g2[t1] ^ g2[t2]);
        S[i] = 1.0f - 2.0f*(float)chip;

        // G1 feedback: stages 3, 10
        unsigned int f1 = g1[3] ^ g1[10];
        // G2 feedback: stages 2, 3, 6, 8, 9, 10
        unsigned int f2 = g2[2] ^ g2[3] ^ g2[6] ^ g2[8] ^ g2[9] ^ g2[10];

        // shift registers
        for (j=10; j>1; j--) {
            g1[j] = g1[j-1];
            g2[j] = g2[j-1];
        }
        g1[1] = f1;
        g2[1] = f2;
    }
    return LIQUID_OK;
}

// initialize DVB-S2 Start-of-Frame sequence (ETSI EN 302 307-1, section 5.5.2):
// 26 bits 18D2E82h (MSB first), pi/2-BPSK modulated as the first part of the
// PLHEADER: even symbol index (0-based): (1-2y)*(+1+j)/sqrt(2),
//           odd  symbol index          : (1-2y)*(-1+j)/sqrt(2)
//  _preamble :   output SOF symbols, [size: 26 x 1]
int scframesync_init_dvbs2_sof(liquid_float_complex * _preamble)
{
    // SOF bit sequence 18D2E82h, MSB first
    static const unsigned int sof_bits = 0x18D2E82;

    float complex * S = (float complex*) _preamble;
    unsigned int i;
    for (i=0; i<DVBS2_SOF_LEN; i++) {
        unsigned int y = (sof_bits >> (DVBS2_SOF_LEN-1-i)) & 1;
        float b = 1.0f - 2.0f*(float)y;
        if ((i % 2) == 0)
            S[i] = b * ( 1.0f + _Complex_I*1.0f) * (float)M_SQRT1_2;
        else
            S[i] = b * (-1.0f + _Complex_I*1.0f) * (float)M_SQRT1_2;
    }
    return LIQUID_OK;
}
