/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-gr_zmq_if
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_GR_ZMQ_IF_API_H
#define INCLUDED_GR_ZMQ_IF_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_gr_zmq_if_EXPORTS
#define GR_ZMQ_IF_API __GR_ATTR_EXPORT
#else
#define GR_ZMQ_IF_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_GR_ZMQ_IF_API_H */
